### ISSUE TITLE
After seeding we get first admin account but waht is the password of first admin

### ISSUE THREAD

**Issue by Darshak-Bali** [Chigozie391/Final-year-project#1]

**Comment by norb-c** [comment]
https://github.com/Chigozie391/Laravel-based-Hostel-management-system/blob/4d9f4faa8202e477b586c7bb9cbef6b543072618/database/factories/AdminFactory.php#L10
Password should be `secret` @Darshak-Bali

**Comment by Darshak-Bali** [comment]
THANKS!!
