### ISSUE TITLE
Admin page not opening

### ISSUE THREAD

**Issue by mehreen1919** [Chigozie391/Final-year-project#3]
I am using Laravel 7.0 and I had to update your project to that version as well. The student registration part is working fine but the admin page gives me this error: **TypeError
Argument 2 passed to Illuminate\Auth\SessionGuard::__construct() must be an instance of Illuminate\Contracts\Auth\UserProvider, null given, called in C:\xampp\htdocs\laravel\hostel\vendor\laravel\framework\src\Illuminate\Auth\AuthManager.php on line 125**
What can I do to solve this?

**Comment by ChigozieL** [comment]
See if this [issue](https://stackoverflow.com/questions/57888578/laravel-argument-2-passed-to-illuminate-auth-sessionguard-construct) fixes this problem

**Comment by mehreen1919** [comment]
Thank you for that link. Another problem has arisen, when I enter the email and password to the admin login page, it gives me the error that the credentials are incorrect.

**Comment by norb-c** [comment]
Confirm that the email and password user are "chigoziemadubuko@gmail.com" and "secret" respectively @mehreen1919

**Comment by mehreen1919** [comment]
> Confirm that the email and password user are "[chigoziemadubuko@gmail.com](mailto:chigoziemadubuko@gmail.com)" and "secret" respectively @mehreen1919

yes, it is. but the error is still there. And can't we change the email if we wanted to.

**Comment by norb-c** [comment]
> > Confirm that the email and password user are "[chigoziemadubuko@gmail.com](mailto:chigoziemadubuko@gmail.com)" and "secret" respectively @mehreen1919
> 
> yes, it is. but the error is still there. And can't we change the email if we wanted to.

Yes please do, also update the password on the database

**Comment by mehreen1919** [comment]
> > > Confirm that the email and password user are "[chigoziemadubuko@gmail.com](mailto:chigoziemadubuko@gmail.com)" and "secret" respectively @mehreen1919
> > 
> > 
> > yes, it is. but the error is still there. And can't we change the email if we wanted to.
> 
> Yes please do, also update the password on the database

what should I change the password to?

**Comment by norb-c** [comment]
Anything you deem fit @mehreen1919

**Comment by mehreen1919** [comment]
it is still not working. says the password confirmation is incorrect.

**Comment by mehreen1919** [comment]
Can you please help me? Sorry for disturbing you again and again.

**Comment by norb-c** [comment]
DId you hash the password? Have you checked how  the password is hashed and stored @mehreen1919

**Comment by mehreen1919** [comment]
yes, it's like this **$2y$10$TKh8H1.PfQx37YgCzwiKb.KjNyWgaHb9cbcoQgdIVFlYg7B77UdFm**

**Comment by mehreen1919** [comment]
??
